## NumPy

NumPy is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions.

### Key Features

- **N-dimensional arrays**: NumPy's core feature is the ndarray, a fast and flexible container for large data sets in Python.

- **Broadcasting**: NumPy can perform operations on arrays of different shapes, making it easy to work with data of varying dimensions.

- **Indexing and slicing**: NumPy provides powerful tools for indexing and slicing arrays, allowing for easy manipulation of data.

- **Vectorization**: NumPy allows for vectorized operations, enabling element-wise operations on arrays without the need for explicit loops.

- **Mathematical functions**: NumPy provides a wide range of mathematical functions for performing operations on arrays, including linear algebra, statistics, and more.
  

In [1]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3])

print(f"Array: {arr1}")
print(f"Type: {type(arr1)}")
print(f"Shape: {arr1.shape}") # Shape means the dimensions of the array
print(f"Dimensions: {arr1.ndim}") # Number of dimensions

Array: [1 2 3]
Type: <class 'numpy.ndarray'>
Shape: (3,)
Dimensions: 1


In [5]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2 = arr2.reshape(1, 5) # Reshape to 1 row and 5 columns

print(f"Array: {arr2}")
print(f"Type: {type(arr2)}")
print(f"Shape: {arr2.shape}")
print(f"Dimensions: {arr2.ndim}")

Array: [[1 2 3 4 5]]
Type: <class 'numpy.ndarray'>
Shape: (1, 5)
Dimensions: 2


In [7]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Array: \n{arr3}")
print(f"Shape: {arr3.shape}")
print(f"Dimensions: {arr3.ndim}")

Array: 
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


In [8]:
arr4 = np.arange(1, 10, 2) # Start at 1, stop before 10, step by 2

print(f"Array: {arr4}")
print(f"Type: {type(arr4)}")
print(f"Shape: {arr4.shape}")
print(f"Dimensions: {arr4.ndim}")


Array: [1 3 5 7 9]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Dimensions: 1


In [9]:
np.arange(1, 10, 2).reshape(5, 1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [11]:
np.ones((3, 4)) # Create an array of ones with shape (3, 4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
## Identity
np.eye(3) # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Array: \n{arr}")
print(f"Shape: {arr.shape}")
print(f"Dimensions: {arr.ndim}")
print(f"Size: {arr.size}") # Total number of elements in the array
print(f"Data Type: {arr.dtype}") # Data type of the elements in the array
print(f"Item Size: {arr.itemsize} bytes") # Size of each element in bytes

Array: 
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64
Item Size: 8 bytes


### Numpy Vectorized Operations

In [18]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

## Element-wise Addition
arr3 = arr1 + arr2
print(f"Element-wise Addition: {arr3}")

## Element-wise Multiplication
arr4 = arr1 * arr2
print(f"Element-wise Multiplication: {arr4}")

## Element-wise Subtraction
arr5 = arr2 - arr1
print(f"Element-wise Subtraction: {arr5}")

## Element-wise Division
arr6 = arr1 / arr2
print(f"Element-wise Division: {arr6}")


Element-wise Addition: [11 22 33 44 55]
Element-wise Multiplication: [ 10  40  90 160 250]
Element-wise Subtraction: [ 9 18 27 36 45]
Element-wise Division: [0.1 0.1 0.1 0.1 0.1]


### Universal Functions (ufuncs)

In [19]:
arr = np.array([1, 2, 3, 4, 5])

## Square root each element
arr_sqrt = np.sqrt(arr)
print(f"Square Root: {arr_sqrt}")

## Exponential (e^x) of each element
arr_exp = np.exp(arr)
print(f"Exponential: {arr_exp}")

## Natural Logarithm (ln) of each element
arr_log = np.log(arr)
print(f"Natural Log: {arr_log}")

## Sine of each element
arr_sin = np.sin(arr)
print(f"Sine: {arr_sin}")


Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


### Array Slicing

In [28]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

## Slicing
print(f"Original Array: \n{arr}")
print(f"Sliced Array (elements 1 to 3): \n{arr[1:4]}") ## Slicing from 1st to 3rd row
print(f"Sliced Array (first 3 elements): \n{arr[:3]}") ## Slicing from 0th to 2nd row
print(f"Sliced Array (last 2 elements): \n{arr[-2:]}") ## Slicing from 1st to 2nd row

Original Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced Array (elements 1 to 3): 
[[ 5  6  7  8]
 [ 9 10 11 12]]
Sliced Array (first 3 elements): 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced Array (last 2 elements): 
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
print(arr[0][0]) ## Accessing the element at 0th row and 0th column

1


In [30]:
print(arr[2][2]) ## Accessing the element at 2nd row and 2nd column

11


In [31]:
print(arr[1:, 2:]) ## Slicing from 1st row and 2nd column

[[ 7  8]
 [11 12]]


In [32]:
print(arr[1:, 2:3])

[[ 7]
 [11]]


In [33]:
## Modify the array
arr[1:, 2:3] = 0
print(arr)

[[ 1  2  3  4]
 [ 5  6  0  8]
 [ 9 10  0 12]]


In [34]:
arr[0, 0] = 20
print(arr)

[[20  2  3  4]
 [ 5  6  0  8]
 [ 9 10  0 12]]


### Statistical Concepts

In [37]:
data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data) ## Mean of the data; sum / count
median = np.median(data) ## Median of the data; middle value
std_dev = np.std(data) ## Standard deviation is a measure of the amount of variation or dispersion of a set of values.
normalized_data = (data - mean) / std_dev ## Normalized data is the data expressed in terms of standard deviations from the mean.
variance = np.var(data) ## Variance is the average of the squared differences from the mean.

print(f"Mean: {mean}\nMedian: {median}\nStandard Deviation: {std_dev}\nNormalized Data: {normalized_data}\nVariance: {variance}")

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Variance: 2.0


### Logical Operations

In [38]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(data[data > 5]) ## Elements greater than 5


[6 7 8]


In [39]:
print(data[(data > 2) & (data < 7)]) ## Elements greater than 2 and less than 7


[3 4 5 6]


In [40]:
data[(data > 2) & (data < 7)]

array([3, 4, 5, 6])