# Numpy Exercise

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

# Create a 5x5 array with random integers between 1 and 20
array_5x5 = np.random.randint(1, 21, size=(5, 5))
array_5x5

array([[ 9, 18, 13,  9, 10],
       [ 4, 12,  7, 12, 17],
       [ 6, 15, 19,  5,  8],
       [17,  4, 11, 12,  3],
       [15, 13,  6,  2, 14]])

In [2]:
# Replace the third column with 1
array_5x5[:, 2] = 1
array_5x5

array([[ 9, 18,  1,  9, 10],
       [ 4, 12,  1, 12, 17],
       [ 6, 15,  1,  5,  8],
       [17,  4,  1, 12,  3],
       [15, 13,  1,  2, 14]])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
array_4x4 = np.arange(1, 17).reshape((4, 4))
array_4x4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
array_4x4[np.diag_indices(4)] = 0
array_4x4

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [6]:
np.fill_diagonal(array_4x4, 0)
array_4x4

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [8]:
array_6x6 = np.arange(1, 37).reshape((6, 6))
array_6x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [9]:
sub_array_3x3 = array_6x6[2:5, 1:4]
sub_array_3x3

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [10]:
array_5x5 = np.random.randint(1, 10, (5, 5))
array_5x5

array([[6, 5, 5, 2, 8],
       [4, 1, 4, 2, 5],
       [8, 4, 5, 9, 8],
       [9, 5, 4, 4, 6],
       [7, 1, 5, 4, 5]])

In [12]:
border_elements = np.concatenate((array_5x5[0, :], array_5x5[-1, :], array_5x5[1:-1, 0], array_5x5[1:-1, -1]))
border_elements

array([6, 5, 5, 2, 8, 7, 1, 5, 4, 5, 4, 8, 9, 5, 8, 6])

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [14]:
array1 = np.random.randint(1, 10, (3, 4))
array2 = np.random.randint(1, 10, (3, 4))
array1, array2

(array([[2, 9, 4, 1],
        [5, 4, 5, 5],
        [1, 9, 9, 1]]),
 array([[5, 5, 6, 6],
        [2, 2, 3, 6],
        [1, 8, 7, 7]]))

In [16]:
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Sum:\n", addition)
print("Difference:\n", subtraction)
print("Product:\n", multiplication)
print("Quotient:\n", division)

Sum:
 [[ 7 14 10  7]
 [ 7  6  8 11]
 [ 2 17 16  8]]
Difference:
 [[-3  4 -2 -5]
 [ 3  2  2 -1]
 [ 0  1  2 -6]]
Product:
 [[10 45 24  6]
 [10  8 15 30]
 [ 1 72 63  7]]
Quotient:
 [[0.4        1.8        0.66666667 0.16666667]
 [2.5        2.         1.66666667 0.83333333]
 [1.         1.125      1.28571429 0.14285714]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [17]:
array_4x4 = np.random.randint(1, 17, (4, 4))
array_4x4

array([[16,  3,  1,  9],
       [ 1,  2,  2,  7],
       [10,  3, 14, 10],
       [ 3,  5,  5, 11]])

In [19]:
row_wise_sum = np.sum(array_4x4, axis=1)
column_wise_sum = np.sum(array_4x4, axis=0)

print("Row-wise sum:\n", row_wise_sum)
print("Column-wise sum:\n", column_wise_sum)


Row-wise sum:
 [29 12 37 24]
Column-wise sum:
 [30 13 22 37]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [20]:
array = np.random.randint(1, 10, size=(5, 5))
mean = np.mean(array) # Mean is sum of elements / number of elements
std = np.std(array) # Standard deviation is a measure of the amount of variation or dispersion of a set of values
median = np.median(array) # Median is the middle value when the elements are sorted
variance = np.var(array) # Variance is the average of the squared differences from the mean

print("Mean:", mean)
print("Standard Deviation:", std)
print("Median:", median)
print("Variance:", variance)


Mean: 5.36
Standard Deviation: 2.88277643947636
Median: 6.0
Variance: 8.3104


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [22]:
array = np.random.randint(1, 10, size=(3, 3))
array

array([[2, 7, 4],
       [7, 1, 8],
       [8, 5, 4]])

In [24]:
normalized_array = (array - np.mean(array)) / np.std(array) # normalized is the array with mean 0 and std 1
normalized_array

array([[-1.2833779 ,  0.77919372, -0.45834925],
       [ 0.77919372, -1.69589222,  1.19170805],
       [ 1.19170805, -0.04583492, -0.45834925]])

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [25]:
array = np.random.randint(1, 10, size=(3, 3))
array

array([[2, 9, 8],
       [9, 2, 6],
       [1, 1, 3]])

In [26]:
x = np.random.randint(1, 10, size=(3,))
x

array([6, 1, 8])

In [28]:
broadcasted_array = array + x
broadcasted_array

array([[ 8, 10, 16],
       [15,  3, 14],
       [ 7,  2, 11]])

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [29]:
array = np.random.randint(1, 10, size=(4, 4))
array

array([[5, 5, 2, 7],
       [9, 5, 6, 6],
       [4, 6, 9, 4],
       [6, 1, 9, 9]])

In [30]:
x = np.random.randint(1, 10, size=(4,))
x

array([4, 2, 1, 5])

In [31]:
broadcasted_array = array - x
broadcasted_array

array([[ 1,  3,  1,  2],
       [ 5,  3,  5,  1],
       [ 0,  4,  8, -1],
       [ 2, -1,  8,  4]])

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [32]:
array = np.random.randint(1, 10, size=(3, 3))
array


array([[6, 7, 9],
       [7, 7, 6],
       [9, 4, 4]])

In [34]:
determinant = np.linalg.det(array)
inverse = np.linalg.inv(array)
eigenvalues = np.linalg.eigvals(array)

print("Determinant:", determinant) # Determinant is a scalar value that can be computed from the elements of a square matrix
print("Inverse:\n", inverse) # Inverse is the matrix that, when multiplied with the original matrix, yields the identity matrix
print("Eigenvalues:", eigenvalues) # Eigenvalues are the roots of the characteristic polynomial

Determinant: -108.99999999999997
Inverse:
 [[-0.03669725 -0.0733945   0.19266055]
 [-0.23853211  0.52293578 -0.24770642]
 [ 0.32110092 -0.35779817  0.06422018]]
Eigenvalues: [19.75758101 -4.10237876  1.34479774]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [48]:
array1 = np.random.randint(1, 10, size=(2, 3))
array2 = np.random.randint(1, 10, size=(3, 2))
result = np.dot(array1, array2)
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Result of Matrix Multiplication:\n", result)

Array 1:
 [[1 8 2]
 [3 8 2]]
Array 2:
 [[7 7]
 [4 8]
 [8 4]]
Result of Matrix Multiplication:
 [[55 79]
 [69 93]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [36]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
array = array.reshape(1, 9)
print(array)

[[1 2 3 4 5 6 7 8 9]]


In [40]:
array = array.reshape(9, 1)
print(array)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [42]:
array = np.random.randint(1, 101, size=(5, 5))
print('Array:\n', array)
array = array.flatten()
print('Flattened Array:\n', array)
array = array.reshape(5, 5)
print('Reshaped Array:\n', array)

Array:
 [[ 58  67  36  56  27]
 [ 73  18  55  99  80]
 [ 24  80  36 100   2]
 [ 41  90   4  73  72]
 [ 71  96  71  89  36]]
Flattened Array:
 [ 58  67  36  56  27  73  18  55  99  80  24  80  36 100   2  41  90   4
  73  72  71  96  71  89  36]
Reshaped Array:
 [[ 58  67  36  56  27]
 [ 73  18  55  99  80]
 [ 24  80  36 100   2]
 [ 41  90   4  73  72]
 [ 71  96  71  89  36]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [43]:
array = np.random.randint(1, 101, size=(5, 5))
print('Array:\n', array)

Array:
 [[39 38 37 87 67]
 [37 47 34  9 37]
 [59  8 71 70 31]
 [ 5 76 75 96 63]
 [99 88 51 83 19]]


In [45]:
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corners:", corners)

Corners: [39 67 99 19]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [46]:
array = np.random.randint(1, 101, size=(4, 4))
print('Array:\n', array)

Array:
 [[74 66 68  2]
 [71 48 79 85]
 [25 32  6 75]
 [86 60 36 47]]


In [47]:
greater_than_ten = array > 10
array[greater_than_ten] = 10
print('Modified Array:\n', array)


Modified Array:
 [[10 10 10  2]
 [10 10 10 10]
 [10 10  6 10]
 [10 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [49]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [50]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [53]:
array = np.random.randint(1, 20, size=(4, 4))
masked_array = np.ma.masked_greater(array, 10)

print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

Original array:
[[ 1 11 10  1]
 [ 4  1 12 18]
 [13 19  9 14]
 [18 19  3 12]]
Masked array:
[[1 -- 10 1]
 [4 1 -- --]
 [-- -- 9 --]
 [-- -- 3 --]]


In [54]:
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:")
print(sum_unmasked)

Sum of unmasked elements:
29


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [56]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = np.ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

Original array:
[[16  7 14]
 [14  8 18]
 [18 20  5]]
Masked array:
[[-- 7 14]
 [14 -- 18]
 [18 20 --]]


In [57]:
# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Modified masked array:
[[15  7 14]
 [14 15 18]
 [18 20 15]]
